language: ruby

rvm:
  - 2.0.0
  - 2.1
  - 2.2.3

before_install:
  - rvm @global do gem uninstall bundler -a -x
  - rvm @global do gem install bundler -v 1.10.6

install:
  - bundle install --without doc guard --jobs 3 --retry 3

script: bundle exec rake
